### ISSUE TITLE
How can import the pnpransac module?

### ISSUE THREAD

**Issue by ghPak1002** [AaltoVision/hscnet#2]
I execute the setup.py in pnpransac folder. Then the .so file is generated in pnpransac folder.

After generation of pnpransac.so, I evaluate the network by following command.

It happens import error such like below things:

(env3.7) ghpak@ghpak-All-Series:~/python_ws/hscnet$ cd pnpransac/
(env3.7) ghpak@ghpak-All-Series:~/python_ws/hscnet/pnpransac$ python setup.py build_ext --inplace
Compiling pnpransacpy.pyx because it changed.
[1/1] Cythonizing pnpransacpy.pyx
/home/ghpak/python_ws/hscnet/env3.7/lib/python3.7/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /home/ghpak/python_ws/hscnet/pnpransac/pnpransacpy.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)
running build_ext
building 'pnpransac' extension
creating build
creating build/temp.linux-x86_64-3.7
x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I. -I/home/ghpak/python_ws/hscnet/env3.7/include -I/home/ghpak/python_ws/hscnet/env3.7/include -I/usr/include/python3.7m -c pnpransacpy.cpp -o build/temp.linux-x86_64-3.7/pnpransacpy.o -fopenmp -std=c++11
In file included from /usr/include/numpy/ndarraytypes.h:1777:0,
                 from /usr/include/numpy/ndarrayobject.h:18,
                 from /usr/include/numpy/arrayobject.h:4,
                 from pnpransacpy.cpp:644:
/usr/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
x86_64-linux-gnu-g++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.7/pnpransacpy.o -L/home/ghpak/python_ws/hscnet/env3.7/lib -lopencv_core -lopencv_calib3d -o /home/ghpak/python_ws/hscnet/pnpransac/pnpransac.cpython-37m-x86_64-linux-gnu.so
(env3.7) ghpak@ghpak-All-Series:~/python_ws/hscnet/pnpransac$ cd ../
(env3.7) ghpak@ghpak-All-Series:~/python_ws/hscnet$ python eval.py --model hscnet --dataset Cambridge --scene KingsCollege --checkpoint Cambridge/hscnet/KingsCollege/ --data_path data/Cambridge/KingsCollege/
Traceback (most recent call last):
  File "eval.py", line 12, in <module>
    from pnpransac import pnpransac
ImportError: ./pnpransac/pnpransac.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN2cv6String10deallocateEv

How can I solve this problem...?

**Comment by lixtgt25** [comment]
Hi,

Have you installed opencv? We assume a conda environment is used and the opencv header and library files can be found in the current conda environment.  So that means the headers should be located in /home/ghpak/python_ws/hscnet/env3.7/include, and libs are in /home/ghpak/python_ws/hscnet/env3.7/lib. If you are not using conda or you have them installed elsewhere, you can change line 10 and line 11 of setup.py to specify the opencv lib and include folders.

**Comment by LLXXTTT** [comment]
Hi,

Have you installed opencv? We assume a conda environment is used and the opencv header and library files can be found in the current conda environment. So that means the headers should be located in /home/ghpak/python_ws/hscnet/env3.7/include, and libs are in /home/ghpak/python_ws/hscnet/env3.7/lib. If you are not using conda or you have them installed elsewhere, you can change line 10 and line 11 of setup.py to specify the opencv lib and include folder.
https://github.com/AaltoVision/hscnet/blob/543ff9f363d78ab61b7c0e88e1909c6f6b856a5a/pnpransac/setup.py#L10
https://github.com/AaltoVision/hscnet/blob/543ff9f363d78ab61b7c0e88e1909c6f6b856a5a/pnpransac/setup.py#L11

**Comment by ghPak1002** [comment]
Hello,

I'm really sorry to respond too late... and THANKS for your pleasure!! :)
I solve that question to use the conda environment.

This issue would be close right now.
